name: petstore_client
version: 1.0.0
description: Petstore client using OpenAPI library
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  openapi:
    path: ../openapi-browser-client
  browser: any
dev_dependencies:
  guinness: '^0.1.17'
